# application.yml
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env, beans, mappings, conditions
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: [livenessState, ping]
        readiness:
          include: [readinessState, db]
      show-details: when-authorized
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8080
  shutdown: graceful